# Generated by Django 4.2.3 on 2023-07-18 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="City",
            new_name="city",
        ),
    ]
